name       : vulkan-tools
version    : 1.2.176.0
release    : 14
source     :
    - https://github.com/KhronosGroup/Vulkan-Tools/archive/refs/tags/sdk-1.2.176.0.tar.gz : 6f8bbf939477f53d081d917722cc6534ceddd059b4674eb96c6da89d140145a9
license    : Apache-2.0
component  : programming.tools
summary    : Vulkan Utilities and Tools
description: |
    This package provides Khronos official Vulkan tools and utilities that can assist development by enabling developers to verify their applications correct use of the Vulkan API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - glslang-devel
    - vulkan-headers
setup      : |
    %cmake_ninja \
        -DGLSLANG_INSTALL_DIR=/usr/bin
build      : |
    %ninja_build
install    : |
    %ninja_install
