name       : vulkan-tools
version    : 1.1.82.0
release    : 1
source     :
    - https://github.com/KhronosGroup/Vulkan-Tools/archive/sdk-1.1.82.0.tar.gz : 22e5e5dfd47535e1664458ee59706abcaace96575d1a3d7fa9ae779a9e83b89c
license    : Apache-2.0
component  : programming.tools
summary    : Vulkan Utilities and Tools
description: |
    This package provides Khronos official Vulkan tools and utilities that can assist development by enabling developers to verify their applications correct use of the Vulkan API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - glslang-devel
setup      : |
    %cmake_ninja \
        -DGLSLANG_INSTALL_DIR=%PREFIX%/bin
build      : |
    %ninja_build
install    : |
    %ninja_install
    mv $installdir/usr/bin/cube $installdir/usr/bin/vulkan-cube
    mv $installdir/usr/bin/cubepp $installdir/usr/bin/vulkan-cubepp
