name       : vulkan-tools
version    : 1.1.92.0
release    : 2
source     :
    - https://github.com/KhronosGroup/Vulkan-Tools/archive/sdk-1.1.92.0.tar.gz : a6f33646f2f5c2474625eb18569e4c621d6d952d465fd05f9ab4a9ece76ba979
license    : Apache-2.0
component  : programming.tools
summary    : Vulkan Utilities and Tools
description: |
    This package provides Khronos official Vulkan tools and utilities that can assist development by enabling developers to verify their applications correct use of the Vulkan API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - glslang-devel
setup      : |
    %cmake_ninja \
        -DGLSLANG_INSTALL_DIR=%PREFIX%/bin
build      : |
    %ninja_build
install    : |
    %ninja_install
