name       : vulkan-tools
version    : 1.3.204.1
release    : 18
source     :
    - git|https://github.com/KhronosGroup/Vulkan-Tools.git : sdk-1.3.204.1
license    : Apache-2.0
component  : programming.tools
summary    : Vulkan Utilities and Tools
description: |
    This package provides Khronos official Vulkan tools and utilities that can assist development by enabling developers to verify their applications correct use of the Vulkan API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-client)
    - pkgconfig(wayland-protocols)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - glslang-devel
    - vulkan-headers
setup      : |
    %cmake_ninja \
        -DGLSLANG_INSTALL_DIR=/usr/bin
build      : |
    %ninja_build
install    : |
    %ninja_install
