name       : vulkan-tools
version    : 1.2.182.0
release    : 15
source     :
    - https://github.com/KhronosGroup/Vulkan-Tools/archive/refs/tags/sdk-1.2.182.0.tar.gz : 584817d57169604f9d568835f907923e7a84dcc014aa19fe44c54fb22b8fb6a4
license    : Apache-2.0
component  : programming.tools
summary    : Vulkan Utilities and Tools
description: |
    This package provides Khronos official Vulkan tools and utilities that can assist development by enabling developers to verify their applications correct use of the Vulkan API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - glslang-devel
    - vulkan-headers
setup      : |
    %cmake_ninja \
        -DGLSLANG_INSTALL_DIR=/usr/bin
build      : |
    %ninja_build
install    : |
    %ninja_install
