name       : vulkan-tools
version    : 1.1.101
release    : 3
source     :
    - https://github.com/KhronosGroup/Vulkan-Tools/archive/v1.1.101.tar.gz : 592fd3596587e522fd22a616c16a38675c55596f651ee628177be5325be36d4f
license    : Apache-2.0
component  : programming.tools
summary    : Vulkan Utilities and Tools
description: |
    This package provides Khronos official Vulkan tools and utilities that can assist development by enabling developers to verify their applications correct use of the Vulkan API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - glslang-devel
setup      : |
    %cmake_ninja \
        -DGLSLANG_INSTALL_DIR=%PREFIX%/bin
build      : |
    %ninja_build
install    : |
    %ninja_install
