name       : vulkan-tools
version    : 1.2.131.1
release    : 6
source     :
    - https://github.com/KhronosGroup/Vulkan-Tools/archive/sdk-1.2.131.1.tar.gz : 1b20ab2e0214966b5503fe2651d8a3d8d0267bfe096732f4871048e30c6bf92c
license    : Apache-2.0
component  : programming.tools
summary    : Vulkan Utilities and Tools
description: |
    This package provides Khronos official Vulkan tools and utilities that can assist development by enabling developers to verify their applications correct use of the Vulkan API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - glslang-devel
    - vulkan-headers
setup      : |
    %cmake_ninja \
        -DGLSLANG_INSTALL_DIR=/usr/bin
build      : |
    %ninja_build
install    : |
    %ninja_install
