name       : vulkan-tools
version    : 1.2.135.0
release    : 7
source     :
    - https://github.com/KhronosGroup/Vulkan-Tools/archive/sdk-1.2.135.0.tar.gz : 83add7b6390ab1eb9b71106b50d7f5ae6afb74374762f0028afc9fdef5380c83
license    : Apache-2.0
component  : programming.tools
summary    : Vulkan Utilities and Tools
description: |
    This package provides Khronos official Vulkan tools and utilities that can assist development by enabling developers to verify their applications correct use of the Vulkan API.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(vulkan)
    - pkgconfig(wayland-client)
    - pkgconfig(x11)
    - pkgconfig(xrandr)
    - glslang-devel
    - vulkan-headers
setup      : |
    %cmake_ninja \
        -DGLSLANG_INSTALL_DIR=/usr/bin
build      : |
    %ninja_build
install    : |
    %ninja_install
